name: secure_share
description: A secure content sharing app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^5.0.3
  http: ^1.6.0
  webview_flutter: ^4.13.1
  provider: ^6.1.5+1
  share_plus: ^12.0.1
  crypto: ^3.0.7
  flutter_secure_storage: ^10.0.0
  connectivity_plus: ^7.0.0
  file_picker: ^10.3.8
  image_picker: ^1.2.1
  shared_preferences: ^2.5.4
  device_info_plus: ^12.3.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
